title: "Geonyeong (Sam) Hong"
author: "Sam Hong"
description: "Sam's Portfolio"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true             # show article excerpts instead of archive list on the home page
show_frame: true                # display a grey frame on large screens
show_sidebar: false             # show a sidebar instead of the usual header
show_minimal: false             # remove all clutter

#show_frame: "/assets/images/background.svg"

# Menu                          # for available icons see https://fontawesome.com/v5/icons/

navigation:                     # accepts {file, title, url, icon, sidebaricon}
  - {file: "Geonyeong (Sam) Hong Resume.pdf", title: "CV"}
  - {file: "AboutMe.md", title: My Info, sidebaricon: address-card}
  - {file: "Projects.md", title: "Projects"}
external:                       # accepts {file, title, url, icon, sidebaricon}
  - {title: Email, url: "mailto:geonyeonghong94@gmail.com"}
  - {title: LinkedIn, url: "https://www.linkedin.com/in/geonyeong-hong-984880344/"}

comments:
#  disqus_shortname: ""         # see https://disqus.com
#  isso_domain: ""              # see https://isso-comments.de

plugins:
 - jekyll-feed
